export const lgaData = {
  abia: [
    { label: "Aba North", value: "aba_north" },
    { label: "Aba South", value: "aba_south" },
    { label: "Arochukwu", value: "arochukwu" },
    { label: "Bende", value: "bende" },
    { label: "Ikwuano", value: "ikwuano" },
    { label: "Isiala Ngwa North", value: "isiala_ngwa_north" },
    { label: "Isiala Ngwa South", value: "isiala_ngwa_south" },
    { label: "Isuikwuato", value: "isuikwuato" },
    { label: "Obi Ngwa", value: "obi_ngwa" },
    { label: "Ohafia", value: "ohafia" },
    { label: "Osisioma", value: "osisioma" },
    { label: "Ugwunagbo", value: "ugwunagbo" },
    { label: "Ukwa East", value: "ukwa_east" },
    { label: "Ukwa West", value: "ukwa_west" },
    { label: "Umuahia North", value: "umuahia_north" },
    { label: "Umuahia South", value: "umuahia_south" },
    { label: "Umu Nneochi", value: "umu_nneochi" },
  ],
  adamawa: [
    { label: "Demsa", value: "demsa" },
    { label: "Fufure", value: "fufure" },
    { label: "Ganye", value: "ganye" },
    { label: "Girei", value: "girei" },
    { label: "Gombi", value: "gombi" },
    { label: "Guyuk", value: "guyuk" },
    { label: "Hong", value: "hong" },
    { label: "Jada", value: "jada" },
    { label: "Lamurde", value: "lamurde" },
    { label: "Madagali", value: "madagali" },
    { label: "Maiha", value: "maiha" },
    { label: "Mayo-Belwa", value: "mayo_belwa" },
    { label: "Michika", value: "michika" },
    { label: "Mubi North", value: "mubi_north" },
    { label: "Mubi South", value: "mubi_south" },
    { label: "Numan", value: "numan" },
    { label: "Shelleng", value: "shelleng" },
    { label: "Song", value: "song" },
    { label: "Toungo", value: "toungo" },
    { label: "Yola North", value: "yola_north" },
    { label: "Yola South", value: "yola_south" },
  ],
  akwa_ibom: [
    { label: "Abak", value: "abak" },
    { label: "Eastern Obolo", value: "eastern_obolo" },
    { label: "Eket", value: "eket" },
    { label: "Esit Eket", value: "esit_eket" },
    { label: "Essien Udim", value: "essien_udim" },
    { label: "Etim Ekpo", value: "etim_ekpo" },
    { label: "Etinan", value: "etinan" },
    { label: "Ibeno", value: "ibeno" },
    { label: "Ibesikpo Asutan", value: "ibesikpo_asutan" },
    { label: "Ibiono-Ibom", value: "ibiono_ibom" },
    { label: "Ika", value: "ika" },
    { label: "Ikono", value: "ikono" },
    { label: "Ikot Abasi", value: "ikot_abasi" },
    { label: "Ikot Ekpene", value: "ikot_ekpene" },
    { label: "Ini", value: "ini" },
    { label: "Itu", value: "itu" },
    { label: "Mbo", value: "mbo" },
    { label: "Mkpat-Enin", value: "mkpat_enin" },
    { label: "Nsit-Atai", value: "nsit_atai" },
    { label: "Nsit Ibom", value: "nsit_ibom" },
    { label: "Nsit Ubium", value: "nsit_ubium" },
    { label: "Obot Akara", value: "obot_akara" },
    { label: "Okobo", value: "okobo" },
    { label: "Onna", value: "onna" },
    { label: "Oron", value: "oron" },
    { label: "Oruk Anam", value: "oruk_anam" },
    { label: "Udung-Uko", value: "udung_uko" },
    { label: "Ukanafun", value: "ukanafun" },
    { label: "Uruan", value: "uruan" },
    { label: "Urue-Offong/Oruko", value: "urue_offong_oruko" },
    { label: "Uyo", value: "uyo" },
  ],
  anambra: [
    { label: "Aguata", value: "aguata" },
    { label: "Anambra East", value: "anambra_east" },
    { label: "Anambra West", value: "anambra_west" },
    { label: "Anaocha", value: "anocha" },
    { label: "Awka North", value: "awka_north" },
    { label: "Awka South", value: "awka_south" },
    { label: "Ayamelum", value: "ayamelum" },
    { label: "Dunukofia", value: "dunukofia" },
    { label: "Ekwusigo", value: "ekwusigo" },
    { label: "Idemili North", value: "idemili_north" },
    { label: "Idemili South", value: "idemili_south" },
    { label: "Ihiala", value: "ihiala" },
    { label: "Njikoka", value: "njikoka" },
    { label: "Nnewi North", value: "nnewi_north" },
    { label: "Nnewi South", value: "nnewi_south" },
    { label: "Ogbaru", value: "ogbaru" },
    { label: "Onitsha North", value: "onitsha_north" },
    { label: "Onitsha South", value: "onitsha_south" },
    { label: "Orumba North", value: "orumba_north" },
    { label: "Orumba South", value: "orumba_south" },
    { label: "Oyi", value: "oyi" },
  ],
  bauchi: [
    { label: "Alkaleri", value: "alkaleri" },
    { label: "Bauchi", value: "bauchi" },
    { label: "Bogoro", value: "bogoro" },
    { label: "Damban", value: "damban" },
    { label: "Darazo", value: "darazo" },
    { label: "Dass", value: "dass" },
    { label: "Gamawa", value: "gamawa" },
    { label: "Ganjuwa", value: "ganjuwa" },
    { label: "Giade", value: "giade" },
    { label: "Itas/Gadau", value: "itas_gadau" },
    { label: "Jama'are", value: "jamaare" },
    { label: "Katagum", value: "katagum" },
    { label: "Kirfi", value: "kirfi" },
    { label: "Misau", value: "misau" },
    { label: "Ningi", value: "ningi" },
    { label: "Shira", value: "shira" },
    { label: "Tafawa Balewa", value: "tafawa_balewa" },
    { label: "Toro", value: "toro" },
    { label: "Warji", value: "warji" },
    { label: "Zaki", value: "zaki" },
  ],
  bayelsa: [
    { label: "Brass", value: "brass" },
    { label: "Ekeremor", value: "ekeremor" },
    { label: "Kolokuma/Opokuma", value: "kolokuma_opokuma" },
    { label: "Nembe", value: "nembe" },
    { label: "Ogbia", value: "ogbia" },
    { label: "Sagbama", value: "sagbama" },
    { label: "Southern Ijaw", value: "southern_ijaw" },
    { label: "Yenagoa", value: "yenagoa" },
  ],
  benue: [
    { label: "Ado", value: "ado" },
    { label: "Agatu", value: "agatu" },
    { label: "Apa", value: "apa" },
    { label: "Buruku", value: "buruku" },
    { label: "Gboko", value: "gboko" },
    { label: "Guma", value: "guma" },
    { label: "Gwer East", value: "gwer_east" },
    { label: "Gwer West", value: "gwer_west" },
    { label: "Katsina-Ala", value: "katsina_ala" },
    { label: "Konshisha", value: "konshisha" },
    { label: "Kwande", value: "kwande" },
    { label: "Logo", value: "logo" },
    { label: "Makurdi", value: "makurdi" },
    { label: "Obi", value: "obi" },
    { label: "Ogbadibo", value: "ogbadibo" },
    { label: "Ohimini", value: "ohimini" },
    { label: "Oju", value: "oju" },
    { label: "Okpokwu", value: "okpokwu" },
    { label: "Otukpo", value: "otukpo" },
    { label: "Tarka", value: "tarka" },
    { label: "Ukum", value: "ukum" },
    { label: "Ushongo", value: "ushongo" },
    { label: "Vandeikya", value: "vandeikya" },
  ],
  borno: [
    { label: "Abadam", value: "abadam" },
    { label: "Askira/Uba", value: "askira_uba" },
    { label: "Bama", value: "bama" },
    { label: "Bayo", value: "bayo" },
    { label: "Biu", value: "biu" },
    { label: "Chibok", value: "chibok" },
    { label: "Damboa", value: "damboa" },
    { label: "Dikwa", value: "dikwa" },
    { label: "Gubio", value: "gubio" },
    { label: "Guzamala", value: "guzamala" },
    { label: "Gwoza", value: "gwoza" },
    { label: "Hawul", value: "hawul" },
    { label: "Jere", value: "jere" },
    { label: "Kaga", value: "kaga" },
    { label: "Kala/Balge", value: "kala_balge" },
    { label: "Konduga", value: "konduga" },
    { label: "Kukawa", value: "kukawa" },
    { label: "Kwaya Kusar", value: "kwaya_kusar" },
    { label: "Mafa", value: "mafa" },
    { label: "Magumeri", value: "magumeri" },
    { label: "Maiduguri", value: "maiduguri" },
    { label: "Marte", value: "marte" },
    { label: "Mobbar", value: "mobbar" },
    { label: "Monguno", value: "monguno" },
    { label: "Ngala", value: "ngala" },
    { label: "Nganzai", value: "nganzai" },
    { label: "Shani", value: "shani" },
  ],
  cross_river: [
    { label: "Abi", value: "abi" },
    { label: "Akamkpa", value: "akamkpa" },
    { label: "Akpabuyo", value: "akpabuyo" },
    { label: "Bakassi", value: "bakassi" },
    { label: "Bekwarra", value: "bekwarra" },
    { label: "Biase", value: "biase" },
    { label: "Boki", value: "boki" },
    { label: "Calabar Municipal", value: "calabar_municipal" },
    { label: "Calabar South", value: "calabar_south" },
    { label: "Etung", value: "etung" },
    { label: "Ikom", value: "ikom" },
    { label: "Obanliku", value: "obanliku" },
    { label: "Obubra", value: "obubra" },
    { label: "Obudu", value: "obudu" },
    { label: "Odukpani", value: "odukpani" },
    { label: "Ogoja", value: "ogoja" },
    { label: "Yakurr", value: "yakurr" },
    { label: "Yala", value: "yala" },
  ],
  delta: [
    { label: "Aniocha North", value: "aniocha_north" },
    { label: "Aniocha South", value: "aniocha_south" },
    { label: "Bomadi", value: "bomadi" },
    { label: "Burutu", value: "burutu" },
    { label: "Ethiope East", value: "ethiope_east" },
    { label: "Ethiope West", value: "ethiope_west" },
    { label: "Ika North East", value: "ika_north_east" },
    { label: "Ika South", value: "ika_south" },
    { label: "Isoko North", value: "isoko_north" },
    { label: "Isoko South", value: "isoko_south" },
    { label: "Ndokwa East", value: "ndokwa_east" },
    { label: "Ndokwa West", value: "ndokwa_west" },
    { label: "Okpe", value: "okpe" },
    { label: "Oshimili North", value: "oshimili_north" },
    { label: "Oshimili South", value: "oshimili_south" },
    { label: "Patani", value: "patani" },
    { label: "Sapele", value: "sapele" },
    { label: "Udu", value: "udu" },
    { label: "Ughelli North", value: "ughelli_north" },
    { label: "Ughelli South", value: "ughelli_south" },
    { label: "Ukwuani", value: "ukwuani" },
    { label: "Uvwie", value: "uvwie" },
    { label: "Warri North", value: "warri_north" },
    { label: "Warri South", value: "warri_south" },
    { label: "Warri South West", value: "warri_south_west" },
  ],
  ebonyi: [
    { label: "Abakaliki", value: "abakaliki" },
    { label: "Afikpo North", value: "afikpo_north" },
    { label: "Afikpo South", value: "afikpo_south" },
    { label: "Ebonyi", value: "ebonyi" },
    { label: "Ezza North", value: "ezza_north" },
    { label: "Ezza South", value: "ezza_south" },
    { label: "Ikwo", value: "ikwo" },
    { label: "Ishielu", value: "ishielu" },
    { label: "Ivo", value: "ivo" },
    { label: "Izzi", value: "izzi" },
    { label: "Ohaozara", value: "ohaozara" },
    { label: "Ohaukwu", value: "ohaukwu" },
    { label: "Onicha", value: "onicha" },
  ],
  edo: [
    { label: "Akoko-Edo", value: "akoko_edo" },
    { label: "Egor", value: "egor" },
    { label: "Esan Central", value: "esan_central" },
    { label: "Esan North-East", value: "esan_north_east" },
    { label: "Esan South-East", value: "esan_south_east" },
    { label: "Esan West", value: "esan_west" },
    { label: "Etsako Central", value: "etsako_central" },
    { label: "Etsako East", value: "etsako_east" },
    { label: "Etsako West", value: "etsako_west" },
    { label: "Igueben", value: "igueben" },
    { label: "Ikpoba-Okha", value: "ikpoba_okha" },
    { label: "Oredo", value: "oredo" },
    { label: "Orhionmwon", value: "orhionmwon" },
    { label: "Ovia North-East", value: "ovia_north_east" },
    { label: "Ovia South-West", value: "ovia_south_west" },
    { label: "Owan East", value: "owan_east" },
    { label: "Owan West", value: "owan_west" },
    { label: "Uhunmwonde", value: "uhunmwonde" },
  ],
  ekiti: [
    { label: "Ado-Ekiti", value: "ado_ekiti" },
    { label: "Efon", value: "efon" },
    { label: "Ekiti East", value: "ekiti_east" },
    { label: "Ekiti South-West", value: "ekiti_south_west" },
    { label: "Ekiti West", value: "ekiti_west" },
    { label: "Emure", value: "emure" },
    { label: "Gbonyin", value: "gbonyin" },
    { label: "Ido Osi", value: "ido_osi" },
    { label: "Ijero", value: "ijero" },
    { label: "Ikere", value: "ikere" },
    { label: "Ikole", value: "ikole" },
    { label: "Ilejemeje", value: "ilejemeje" },
    { label: "Irepodun/Ifelodun", value: "irepodun_ifelodun" },
    { label: "Ise/Orun", value: "ise_orun" },
    { label: "Moba", value: "moba" },
    { label: "Oye", value: "oye" },
  ],
  enugu: [
    { label: "Aninri", value: "aninri" },
    { label: "Awgu", value: "awgu" },
    { label: "Enugu East", value: "enugu_east" },
    { label: "Enugu North", value: "enugu_north" },
    { label: "Enugu South", value: "enugu_south" },
    { label: "Ezeagu", value: "ezeagu" },
    { label: "Igbo Etiti", value: "igbo_etiti" },
    { label: "Igbo Eze North", value: "igbo_eze_north" },
    { label: "Igbo Eze South", value: "igbo_eze_south" },
    { label: "Isi Uzo", value: "isi_uzo" },
    { label: "Nkanu East", value: "nkanu_east" },
    { label: "Nkanu West", value: "nkanu_west" },
    { label: "Nsukka", value: "nsukka" },
    { label: "Oji River", value: "oji_river" },
    { label: "Udenu", value: "udenu" },
    { label: "Udi", value: "udi" },
    { label: "Uzouwani", value: "uzouwani" },
  ],
  gombe: [
    { label: "Akko", value: "akko" },
    { label: "Balanga", value: "balanga" },
    { label: "Billiri", value: "billiri" },
    { label: "Dukku", value: "dukku" },
    { label: "Funakaye", value: "funakaye" },
    { label: "Gombe", value: "gombe" },
    { label: "Kaltungo", value: "kaltungo" },
    { label: "Kano", value: "kano" },
    { label: "Nafada", value: "nafada" },
    { label: "Shongom", value: "shongom" },
    { label: "Yamaltu/Deba", value: "yamaltu_deba" },
  ],
  imo: [
    { label: "Ahiazu Mbaise", value: "ahiazu_mbaise" },
    { label: "Aboh Mbaise", value: "aboh_mbaise" },
    { label: "Ihitte/Uboma", value: "ihitte_uboma" },
    { label: "Ikeduru", value: "ikeduru" },
    { label: "Ikwuano", value: "ikwuano" },
    { label: "Mbaitoli", value: "mbaitoli" },
    { label: "Mbaise", value: "mbaise" },
    { label: "Ngor Okpala", value: "ngor_okpala" },
    { label: "Nkwerre", value: "nkwerre" },
    { label: "Nwangele", value: "nwangele" },
    { label: "Obowo", value: "obowo" },
    { label: "Oguta", value: "oguta" },
    { label: "Ohaji/Egbema", value: "ohaji_egbema" },
    { label: "Okigwe", value: "okigwe" },
    { label: "Orlu", value: "orlu" },
    { label: "Orsu", value: "orsu" },
    { label: "Owerri Municipal", value: "owerri_municipal" },
    { label: "Owerri North", value: "owerri_north" },
    { label: "Owerri West", value: "owerri_west" },
  ],
  jigawa: [
    { label: "Auyo", value: "auyo" },
    { label: "Babura", value: "babura" },
    { label: "Biriniwa", value: "biriniwa" },
    { label: "Birnin Kudu", value: "birnin_kudu" },
    { label: "Buji", value: "buji" },
    { label: "Dutse", value: "dutse" },
    { label: "Gagarawa", value: "gagarawa" },
    { label: "Garki", value: "garki" },
    { label: "Gumel", value: "gumel" },
    { label: "Guri", value: "guri" },
    { label: "Gwaram", value: "gwaram" },
    { label: "Gwiwa", value: "gwiwa" },
    { label: "Hadejia", value: "hadejia" },
    { label: "Jahun", value: "jahun" },
    { label: "Kafin Hausa", value: "kafin_haus" },
    { label: "Kaugama", value: "kaugama" },
    { label: "Kazaure", value: "kazaure" },
    { label: "Kirikasamma", value: "kirikasamma" },
    { label: "Malam Madori", value: "malam_madori" },
    { label: "Miga", value: "miga" },
    { label: "Roni", value: "roni" },
    { label: "Sule Tankarkar", value: "sule_tankarkar" },
    { label: "Taura", value: "taura" },
    { label: "Zaki Biam", value: "zaki_biam" },
  ],
  kaduna: [
    { label: "Birnin Gwari", value: "birnin_gwari" },
    { label: "Chikun", value: "chikun" },
    { label: "Giwa", value: "giwa" },
    { label: "Jaba", value: "jaba" },
    { label: "Jema'a", value: "jemaa" },
    { label: "Kachia", value: "kachia" },
    { label: "Kaduna North", value: "kaduna_north" },
    { label: "Kaduna South", value: "kaduna_south" },
    { label: "Kagarko", value: "kagarko" },
    { label: "Kajuru", value: "kajuru" },
    { label: "Kaura", value: "kaura" },
    { label: "Kauru", value: "kauru" },
    { label: "Kubau", value: "kubau" },
    { label: "Kudan", value: "kudan" },
    { label: "Lere", value: "lere" },
    { label: "Makarfi", value: "makarfi" },
    { label: "Sabon Gari", value: "sabon_gari" },
    { label: "Sanga", value: "sanga" },
    { label: "Soba", value: "soba" },
    { label: "Zangon Kataf", value: "zangon_kataf" },
    { label: "Zaria", value: "zaria" },
  ],
  kano: [
    { label: "Ajingi", value: "ajingi" },
    { label: "Albasu", value: "albasu" },
    { label: "Bagwai", value: "bagwai" },
    { label: "Bebeji", value: "bebeji" },
    { label: "Bichi", value: "bichi" },
    { label: "Bunkure", value: "bunkure" },
    { label: "Dala", value: "dala" },
    { label: "Dambatta", value: "dambatta" },
    { label: "Dawakin Kudu", value: "dawakin_kudu" },
    { label: "Dawakin Tofa", value: "dawakin_tofa" },
    { label: "Doguwa", value: "doguwa" },
    { label: "Fagge", value: "fagge" },
    { label: "Gabasawa", value: "gabasawa" },
    { label: "Garko", value: "garko" },
    { label: "Garun Mallam", value: "garun_mallam" },
    { label: "Gaya", value: "gaya" },
    { label: "Gezawa", value: "gezawa" },
    { label: "Gwarzo", value: "gwarzo" },
    { label: "Kano Municipal", value: "kano_municipal" },
    { label: "Karaye", value: "karaye" },
    { label: "Kibiya", value: "kibiya" },
    { label: "Kiru", value: "kiru" },
    { label: "Kumbotso", value: "kumbotso" },
    { label: "Kunchi", value: "kunchi" },
    { label: "Kura", value: "kura" },
    { label: "Madobi", value: "madobi" },
    { label: "Makoda", value: "makoda" },
    { label: "Minjibir", value: "minjibir" },
    { label: "Nasarawa", value: "nasarawa" },
    { label: "Rimin Gado", value: "rimin_gado" },
    { label: "Rogo", value: "rogo" },
    { label: "Tarauni", value: "tarauni" },
    { label: "Tofa", value: "tofa" },
    { label: "Tsanyawa", value: "tsanyawa" },
    { label: "Ungogo", value: "ungogo" },
    { label: "Warawa", value: "warawa" },
    { label: "Wudil", value: "wudil" },
  ],
  katsina: [
    { label: "Bakori", value: "bakori" },
    { label: "Batagarawa", value: "batagarawa" },
    { label: "Batsari", value: "batsari" },
    { label: "Baure", value: "baure" },
    { label: "Bindawa", value: "bindawa" },
    { label: "Charanchi", value: "charanchi" },
    { label: "Dandume", value: "dandume" },
    { label: "Danja", value: "danja" },
    { label: "Danmusa", value: "danmusa" },
    { label: "Dutsin-Ma", value: "dutsin_ma" },
    { label: "Faskari", value: "faskari" },
    { label: "Funtua", value: "funtua" },
    { label: "Kafur", value: "kafur" },
    { label: "Kaita", value: "kaita" },
    { label: "Kankara", value: "kankara" },
    { label: "Kankia", value: "kankia" },
    { label: "Katsina", value: "katsina" },
    { label: "Kurfi", value: "kurfi" },
    { label: "Kusada", value: "kusada" },
    { label: "Mai'aduwa", value: "maiaduwa" },
    { label: "Malumfashi", value: "malumfashi" },
    { label: "Mani", value: "mani" },
    { label: "Mashi", value: "mashi" },
    { label: "Matazu", value: "matazu" },
    { label: "Musawa", value: "musawa" },
    { label: "Rimi", value: "rimi" },
    { label: "Sabuwa", value: "sabuwa" },
    { label: "Safana", value: "safana" },
    { label: "Sandamu", value: "sandamu" },
    { label: "Zango", value: "zango" },
  ],
  kebbi: [
    { label: "Aleiro", value: "aleiro" },
    { label: "Bagudo", value: "bagudo" },
    { label: "Birnin Kebbi", value: "birnin_kebbi" },
    { label: "Bunza", value: "bunza" },
    { label: "Dandi", value: "dandi" },
    { label: "Danko/Wasagu", value: "danko_wasagu" },
    { label: "Fakai", value: "fakai" },
    { label: "Gwandu", value: "gwandu" },
    { label: "Jega", value: "jega" },
    { label: "Kamba", value: "kamba" },
    { label: "Koko/Besse", value: "koko_besse" },
    { label: "Maiyama", value: "maiyama" },
    { label: "Ngaski", value: "ngaski" },
    { label: "Sakaba", value: "sakaba" },
    { label: "Suru", value: "suru" },
    { label: "Yauri", value: "yauri" },
    { label: "Zuru", value: "zuru" },
  ],
  kogi: [
    { label: "Adavi", value: "adavi" },
    { label: "Ajaokuta", value: "ajaokuta" },
    { label: "Ankpa", value: "ankpa" },
    { label: "Bassa", value: "bassa" },
    { label: "Dekina", value: "dekina" },
    { label: "Ibaji", value: "ibaji" },
    { label: "Idah", value: "idah" },
    { label: "Igalamela/Odolu", value: "igalamela_odolu" },
    { label: "Ileje", value: "ileje" },
    { label: "Kogi", value: "kogi" },
    { label: "Okene", value: "okene" },
    { label: "Okehi", value: "okehi" },
    { label: "Olamaboro", value: "olamaboro" },
    { label: "Omala", value: "omala" },
    { label: "Yagba East", value: "yagba_east" },
    { label: "Yagba West", value: "yagba_west" },
  ],
  kwara: [
    { label: "Asa", value: "asa" },
    { label: "Baruten", value: "baruten" },
    { label: "Ekiti", value: "ekiti" },
    { label: "Ifelodun", value: "ifelodun" },
    { label: "Ilorin East", value: "ilorin_east" },
    { label: "Ilorin South", value: "ilorin_south" },
    { label: "Ilorin West", value: "ilorin_west" },
    { label: "Irepodun", value: "irepodun" },
    { label: "Isin", value: "isin" },
    { label: "Kaiama", value: "kaiama" },
    { label: "Moro", value: "moro" },
    { label: "Offa", value: "offa" },
    { label: "Oke-Ero", value: "oke_ero" },
    { label: "Oyun", value: "oyun" },
    { label: "Pategi", value: "pategi" },
  ],
  lagos: [
    { label: "Agege", value: "agege" },
    { label: "Ajeromi/Ifelodun", value: "ajeromi_ifelodun" },
    { label: "Alimosho", value: "alimosho" },
    { label: "Apapa", value: "apapa" },
    { label: "Eti-Osa", value: "eti_osa" },
    { label: "Ikeja", value: "ikeja" },
    { label: "Ikorodu", value: "ikorodu" },
    { label: "Lagos Island", value: "lagos_island" },
    { label: "Lagos Mainland", value: "lagos_mainland" },
    { label: "Mushin", value: "mushin" },
    { label: "Ojo", value: "ojo" },
    { label: "Oshodi-Isolo", value: "oshodi_isolo" },
    { label: "Shomolu", value: "shomolu" },
    { label: "Surulere", value: "surulere" },
  ],
  nasarawa: [
    { label: "Akwanga", value: "akwanga" },
    { label: "Annual", value: "annual" },
    { label: "Doma", value: "doma" },
    { label: "Karu", value: "karu" },
    { label: "Keana", value: "keana" },
    { label: "Keffi", value: "keffi" },
    { label: "Kokona", value: "kokona" },
    { label: "Nasarawa", value: "nasarawa" },
    { label: "Nassarawa", value: "nassarawa" },
    { label: "Toto", value: "toto" },
    { label: "Wamba", value: "wamba" },
  ],
  niger: [
    { label: "Agwara", value: "agwara" },
    { label: "Bida", value: "bida" },
    { label: "Borgu", value: "borgu" },
    { label: "Bosso", value: "bosso" },
    { label: "Chanchaga", value: "chanchaga" },
    { label: "Edati", value: "edati" },
    { label: "Gbako", value: "gbako" },
    { label: "Gbara", value: "gbara" },
    { label: "Katcha", value: "katcha" },
    { label: "Lapai", value: "lapai" },
    { label: "Laval", value: "laval" },
    { label: "Mokwa", value: "mokwa" },
    { label: "Mashegu", value: "mashegu" },
    { label: "Munya", value: "munya" },
    { label: "Rafi", value: "rafi" },
    { label: "Rijau", value: "rijau" },
    { label: "Shiroro", value: "shiroro" },
    { label: "Suleja", value: "suleja" },
    { label: "Wushishi", value: "wushishi" },
  ],
  oyo: [
    { label: "Akinyele", value: "akinselye" },
    { label: "Atiba", value: "atiba" },
    { label: "Atisbo", value: "atisbo" },
    { label: "Egbeda", value: "egbeda" },
    { label: "Ibadan North", value: "ibadan_north" },
    { label: "Ibadan North East", value: "ibadan_north_east" },
    { label: "Ibadan North West", value: "ibadan_north_west" },
    { label: "Ibadan South East", value: "ibadan_south_east" },
    { label: "Ibadan South West", value: "ibadan_south_west" },
    { label: "Ibarapa Central", value: "ibarapa_central" },
    { label: "Ibarapa East", value: "ibarapa_east" },
    { label: "Ibarapa North", value: "ibarapa_north" },
    { label: "Ido", value: "ido" },
    { label: "Irepo", value: "irepo" },
    { label: "Iseyin", value: "iseyin" },
    { label: "Itesiwaju", value: "itesiwaju" },
    { label: "Kajola", value: "kajola" },
    { label: "Lagelu", value: "lagelu" },
    { label: "Ogbomosho North", value: "ogbomosho_north" },
    { label: "Ogbomosho South", value: "ogbomosho_south" },
    { label: "Oyo East", value: "oyo_east" },
    { label: "Oyo West", value: "oyo_west" },
  ],
  plateau: [
    { label: "Barkin Ladi", value: "barkin_ladi" },
    { label: "Bassa", value: "bassa" },
    { label: "Bokkos", value: "bokkos" },
    { label: "Bunkure", value: "bunkure" },
    { label: "Jos East", value: "jos_east" },
    { label: "Jos North", value: "jos_north" },
    { label: "Jos South", value: "jos_south" },
    { label: "Kanam", value: "kanam" },
    { label: "Kanke", value: "kanke" },
    { label: "Langtang North", value: "langtang_north" },
    { label: "Langtang South", value: "langtang_south" },
    { label: "Mangu", value: "mangu" },
    { label: "Pankshin", value: "pankshin" },
    { label: "Qua'an Pan", value: "quaan_pan" },
    { label: "Riyom", value: "riyom" },
    { label: "Shendam", value: "shendam" },
    { label: "Wase", value: "wase" },
  ],
  rivers: [
    { label: "Ahoada East", value: "ahoada_east" },
    { label: "Ahoada West", value: "ahoada_west" },
    { label: "Akuku Toru", value: "akuku_toru" },
    { label: "Andoni", value: "andoni" },
    { label: "Asari-Toru", value: "asari_toru" },
    { label: "Bonny", value: "bonny" },
    { label: "Degema", value: "degema" },
    { label: "Eleme", value: "eleme" },
    { label: "Emohua", value: "emohua" },
    { label: "Etche", value: "etche" },
    { label: "Gokana", value: "gokana" },
    { label: "Ikwerre", value: "ikwerre" },
    { label: "Khana", value: "khana" },
    { label: "Obio-Akpor", value: "obio_akpor" },
    { label: "Ogba/Egbema/Ndoni", value: "ogba_egbema_ndoni" },
    { label: "Ogu/Bolo", value: "ogu_bolo" },
    { label: "Okrika", value: "okrika" },
    { label: "Omuma", value: "omuma" },
    { label: "Opobo/Nkoro", value: "opobo_nkoro" },
    { label: "Port Harcourt", value: "port_harcourt" },
    { label: "Tai", value: "tai" },
  ],
  sokoto: [
    { label: "Binji", value: "binji" },
    { label: "Bodinga", value: "bodinga" },
    { label: "Dange-Shuni", value: "dange_shuni" },
    { label: "Gada", value: "gada" },
    { label: "Goronyo", value: "goronyo" },
    { label: "Gudu", value: "gudu" },
    { label: "Illela", value: "illela" },
    { label: "Kebbe", value: "kebbe" },
    { label: "Kware", value: "kware" },
    { label: "Rabah", value: "rabah" },
    { label: "Sabon Birni", value: "sabon_birni" },
    { label: "Sokoto North", value: "sokoto_north" },
    { label: "Sokoto South", value: "sokoto_south" },
    { label: "Tambuwal", value: "tambuwal" },
    { label: "Tureta", value: "tureta" },
    { label: "Wamako", value: "wamako" },
    { label: "Wurno", value: "wurno" },
    { label: "Yabo", value: "yabo" },
  ],
  taraba: [
    { label: "Ardo-Kola", value: "ardo_kola" },
    { label: "Donga", value: "donga" },
    { label: "Gashaka", value: "gashaka" },
    { label: "Gassol", value: "gassol" },
    { label: "Ibi", value: "ibi" },
    { label: "Jalingo", value: "jalingo" },
    { label: "Karin-Lamido", value: "karin_lamido" },
    { label: "Lau", value: "lau" },
    { label: "Niger", value: "niger" },
    { label: "Sardauna", value: "sardauna" },
    { label: "Takum", value: "takum" },
    { label: "Ussa", value: "ussa" },
    { label: "Wukari", value: "wukari" },
    { label: "Yorro", value: "yorro" },
    { label: "Zing", value: "zing" },
  ],
  yobe: [
    { label: "Bade", value: "bade" },
    { label: "Bursari", value: "bursari" },
    { label: "Damaturu", value: "damaturu" },
    { label: "Fika", value: "fika" },
    { label: "Fune", value: "fune" },
    { label: "Geidam", value: "geidam" },
    { label: "Gujba", value: "gujba" },
    { label: "Gulani", value: "gulani" },
    { label: "Jakusko", value: "jakusko" },
    { label: "Karasuwa", value: "karasuwa" },
    { label: "Machina", value: "machina" },
    { label: "Nangere", value: "nangere" },
    { label: "Nguru", value: "nguru" },
    { label: "Potiskum", value: "potiskum" },
    { label: "Tarmuwa", value: "tarmuwa" },
    { label: "Yunusari", value: "yunusari" },
    { label: "Yusufari", value: "yusufari" },
  ],
  zamfara: [
    { label: "Anka", value: "anka" },
    { label: "Bakura", value: "bakura" },
    { label: "Birnin Magaji", value: "birnin_magaji" },
    { label: "Bukkuyum", value: "bukkuyum" },
    { label: "Buruku", value: "buruku" },
    { label: "Chafe", value: "chafe" },
    { label: "Gummi", value: "gummi" },
    { label: "Gusau", value: "gusau" },
    { label: "Kaura Namoda", value: "kaura_namoda" },
    { label: "Maradun", value: "maradun" },
    { label: "Maru", value: "maru" },
    { label: "Shinkafi", value: "shinkafi" },
    { label: "Talata Mafara", value: "talata_mafara" },
    { label: "Zurmi", value: "zurmi" },
  ],
};
